
import { AppLanguage, Translations } from './types';

export const TRANSLATIONS: Record<AppLanguage, Translations> = {
  [AppLanguage.ENGLISH]: {
    masterList: 'Master List',
    bqBuilder: 'BQ Builder',
    quotationView: 'Quotation View',
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    selectLanguage: 'Select Language',
    version: 'Version',
    appearance: 'Appearance',
    general: 'General',
    system: 'System',
    clientName: 'Client Name',
    date: 'Date',
    quoteId: 'Quote ID',
    category: 'Category',
    item: 'Item',
    description: 'Description',
    typeColumn: 'Type',
    price: 'Price',
    qty: 'Qty',
    uom: 'UOM',
    total: 'Total',
    actions: 'Actions',
    addRow: 'Add Item',
    delete: 'Delete',
    subtotal: 'Subtotal',
    tax: 'Tax',
    grandTotal: 'Grand Total',
    companyName: 'Company Name',
    companyAddress: 'Address',
    currencySymbol: 'Currency Symbol',
    exportPDF: 'Export PDF',
    noData: 'No items found. Go to BQ Builder to add items.',
    brand: 'Brand',
    axsku: 'AX SKU',
    mpn: 'MPN',
    group: 'Group',
    rexScFob: 'REX SC (FOB)',
    forex: 'Forex',
    sst: 'SST',
    opta: 'OPTA',
    rexScDdp: 'REX SC (DDP)',
    rexSp: 'REX SP',
    rexRsp: 'REX RSP',
    projects: 'Projects',
    addProject: 'Add Project',
    projectName: 'Project Name',
    validityPeriod: 'Validity Period',
    backToProjects: 'Back to Projects',
    rexTsc: 'REX TSC',
    rexTsp: 'REX TSP',
    rexTrsp: 'REX TRSP',
    rexGp: 'REX GP',
    rexGpPercent: 'REX GP%',
    createProject: 'Create Project',
    searchProjects: 'Search Projects...',
    clientContact: 'Client Contact',
    clientAddress: 'Client Address',
    editDetails: 'Edit Details',
    updateProject: 'Update Project',
    projectDetails: 'Project Details',
    profileSettings: 'Profile Information',
    yourName: 'Your Name',
    yourContact: 'Your Contact Number',
    profileRole: 'Role',
    confirm: 'Confirm Changes',
    roleAdmin: 'Admin',
    roleUser: 'User',
    columns: 'Columns',
    isOptional: 'Optional',
    bankName: 'Bank Name',
    bankAccount: 'Bank Account Number',
  },
  [AppLanguage.MALAY]: {
    masterList: 'Senarai Induk',
    bqBuilder: 'Pembina BQ',
    quotationView: 'Paparan Sebut Harga',
    settings: 'Tetapan',
    theme: 'Tema',
    language: 'Bahasa',
    darkMode: 'Mod Gelap',
    lightMode: 'Mod Cerah',
    selectLanguage: 'Pilih Bahasa',
    version: 'Versi',
    appearance: 'Penampilan',
    general: 'Umum',
    system: 'Sistem',
    clientName: 'Nama Pelanggan',
    date: 'Tarikh',
    quoteId: 'ID Sebut Harga',
    category: 'Kategori',
    item: 'Item',
    description: 'Penerangan',
    typeColumn: 'Jenis',
    price: 'Harga',
    qty: 'Kuantiti',
    uom: 'Unit',
    total: 'Jumlah',
    actions: 'Tindakan',
    addRow: 'Tambah Item',
    delete: 'Padam',
    subtotal: 'Jumlah Kecil',
    tax: 'Cukai',
    grandTotal: 'Jumlah Besar',
    companyName: 'Nama Syarikat',
    companyAddress: 'Alamat',
    currencySymbol: 'Simbol Mata Wang',
    exportPDF: 'Eksport PDF',
    noData: 'Tiada item dijumpai. Pergi ke Pembina BQ untuk menambah item.',
    brand: 'Brand',
    axsku: 'AX SKU',
    mpn: 'MPN',
    group: 'Group',
    rexScFob: 'REX SC (FOB)',
    forex: 'Forex',
    sst: 'SST',
    opta: 'OPTA',
    rexScDdp: 'REX SC (DDP)',
    rexSp: 'REX SP',
    rexRsp: 'REX RSP',
    projects: 'Projek',
    addProject: 'Tambah Projek',
    projectName: 'Nama Projek',
    validityPeriod: 'Tempoh Sah',
    backToProjects: 'Kembali ke Projek',
    rexTsc: 'REX TSC',
    rexTsp: 'REX TSP',
    rexTrsp: 'REX TRSP',
    rexGp: 'REX GP',
    rexGpPercent: 'REX GP%',
    createProject: 'Cipta Projek',
    searchProjects: 'Cari Projek...',
    clientContact: 'No. Telefon Pelanggan',
    clientAddress: 'Alamat Pelanggan',
    editDetails: 'Sunting Butiran',
    updateProject: 'Kemaskini Projek',
    projectDetails: 'Butiran Projek',
    profileSettings: 'Maklumat Profil',
    yourName: 'Nama Anda',
    yourContact: 'Nombor Telefon Anda',
    profileRole: 'Peranan',
    confirm: 'Sahkan Perubahan',
    roleAdmin: 'Pentadbir',
    roleUser: 'Pengguna',
    columns: 'Lajur',
    isOptional: 'Pilihan',
    bankName: 'Nama Bank',
    bankAccount: 'Nombor Akaun Bank',
  },
  [AppLanguage.CHINESE]: {
    masterList: '总表',
    bqBuilder: 'BQ 构建器',
    quotationView: '报价视图',
    settings: '设置',
    theme: '主题',
    language: '语言',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    selectLanguage: '选择语言',
    version: '版本',
    appearance: '外观',
    general: '常规',
    system: '系统',
    clientName: '客户名称',
    date: '日期',
    quoteId: '报价 ID',
    category: '类别',
    item: '项目',
    description: '描述',
    typeColumn: '类型',
    price: '价格',
    qty: '数量',
    uom: '单位',
    total: '总计',
    actions: '操作',
    addRow: '添加项目',
    delete: '删除',
    subtotal: '小计',
    tax: '税',
    grandTotal: '总计',
    companyName: '公司名称',
    companyAddress: '地址',
    currencySymbol: '货币符号',
    exportPDF: '导出 PDF',
    noData: '未找到项目。请前往 BQ 构建器添加项目。',
    brand: '品牌 (Brand)',
    axsku: 'AX SKU',
    mpn: 'MPN',
    group: '组 (Group)',
    rexScFob: 'REX SC (FOB)',
    forex: '外汇',
    sst: 'SST',
    opta: 'OPTA',
    rexScDdp: 'REX SC (DDP)',
    rexSp: 'REX SP',
    rexRsp: 'REX RSP',
    projects: '项目',
    addProject: '添加项目',
    projectName: '项目名称',
    validityPeriod: '有效期',
    backToProjects: '返回项目',
    rexTsc: 'REX TSC',
    rexTsp: 'REX TSP',
    rexTrsp: 'REX TRSP',
    rexGp: 'REX GP',
    rexGpPercent: 'REX GP%',
    createProject: '创建项目',
    searchProjects: '搜索项目...',
    clientContact: '客户联系电话',
    clientAddress: '客户地址',
    editDetails: '编辑详情',
    updateProject: '更新项目',
    projectDetails: '项目详情',
    profileSettings: '个人资料信息',
    yourName: '您的姓名',
    yourContact: '您的联系电话',
    profileRole: '角色',
    confirm: '确认更改',
    roleAdmin: '管理员',
    roleUser: '用户',
    columns: '列',
    isOptional: '可选',
    bankName: '银行名称',
    bankAccount: '银行账号',
  },
};
