
export const ITEM_STRATEGIES = [
    // 1
    { ddp: "Formula C", sp: "Formula C", rsp: "Formula A" },
    { ddp: "Formula C", sp: "Formula C", rsp: "Formula A" },
    { ddp: "Formula C", sp: "Formula C", rsp: "Formula A" },
    { ddp: "Formula B", sp: "Formula B", rsp: "1100" },
    { ddp: "Formula B", sp: "Formula B", rsp: "1100" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 10
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula C", sp: "Formula C", rsp: "70000" },
    { ddp: "Formula C", sp: "Formula C", rsp: "3399" },
    { ddp: "Formula C", sp: "Formula C", rsp: "3399" },
    { ddp: "Formula C", sp: "Formula C", rsp: "3399" },
    { ddp: "Formula C", sp: "Formula C", rsp: "3399" },
    { ddp: "Formula C", sp: "Formula C", rsp: "25999" },
    { ddp: "Formula C", sp: "Formula C", rsp: "90000" },
    { ddp: "Formula C", sp: "Formula C", rsp: "51900" },
    { ddp: "Formula C", sp: "Formula C", rsp: "3399" },
    // 20
    { ddp: "Formula C", sp: "Formula C", rsp: "51900" },
    { ddp: "Formula C", sp: "Formula C", rsp: "121500" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula C", rsp: "1299" },
    { ddp: "Formula A", sp: "Formula C", rsp: "2000" },
    { ddp: "Formula A", sp: "Formula C", rsp: "1599" },
    { ddp: "1500", sp: "Formula C", rsp: "2499" },
    { ddp: "1280", sp: "Formula C", rsp: "2000" },
    { ddp: "Formula A", sp: "Formula C", rsp: "17699" },
    // 30
    { ddp: "Formula A", sp: "Formula C", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula C", rsp: "12000" },
    { ddp: "Formula A", sp: "Formula C", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula F", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula F", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula C", rsp: "55000" },
    { ddp: "Formula A", sp: "Formula C", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula F", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula C", rsp: "69000" },
    { ddp: "Formula A", sp: "Formula C", rsp: "Formula A" },
    // 40
    { ddp: "Formula A", sp: "Formula C", rsp: "83000" },
    { ddp: "Formula A", sp: "Formula F", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula F", rsp: "95000" },
    { ddp: "Formula A", sp: "Formula F", rsp: "119000" },
    { ddp: "Formula A", sp: "Formula F", rsp: "135799" },
    { ddp: "Formula A", sp: "Formula F", rsp: "36999" },
    { ddp: "Formula A", sp: "Formula F", rsp: "39999" },
    { ddp: "Formula C", sp: "Formula F", rsp: "2099" },
    { ddp: "Formula D", sp: "Formula C", rsp: "38000" },
    { ddp: "Formula C", sp: "Formula F", rsp: "2099" },
    // 50
    { ddp: "Formula C", sp: "Formula F", rsp: "2899" },
    { ddp: "Formula C", sp: "Formula C", rsp: "19000" },
    { ddp: "Formula D", sp: "Formula C", rsp: "Formula A" },
    { ddp: "Formula D", sp: "Formula C", rsp: "Formula A" },
    { ddp: "Formula D", sp: "Formula C", rsp: "Formula A" },
    { ddp: "Formula D", sp: "Formula F", rsp: "149999" },
    { ddp: "Formula D", sp: "Formula F", rsp: "149999" },
    { ddp: "Formula D", sp: "Formula F", rsp: "149999" },
    { ddp: "Formula D", sp: "Formula F", rsp: "149999" },
    { ddp: "Formula D", sp: "Formula F", rsp: "149999" },
    // 60
    { ddp: "Formula D", sp: "Formula F", rsp: "149999" },
    { ddp: "Formula D", sp: "Formula F", rsp: "149999" },
    { ddp: "Formula C", sp: "Formula C", rsp: "16000" },
    { ddp: "Formula C", sp: "Formula C", rsp: "19000" },
    { ddp: "Formula C", sp: "Formula F", rsp: "34999" },
    { ddp: "Formula C", sp: "Formula F", rsp: "38999" },
    { ddp: "Formula D", sp: "Formula F", rsp: "38000" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 70
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 80
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 90
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 100
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 110
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 120
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 130
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 140
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 150
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 160
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 170
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 180
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 190
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 200
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 210
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "27.33", sp: "39.1", rsp: "39.1" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 220
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 230
    { ddp: "155.44", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "155.44", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "155.44", sp: "Formula B", rsp: "Formula A" },
    // 240
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 250
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 260
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 270
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 280
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 290
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "250" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "3999" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 300
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 310
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 320
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    // 330
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    // 340
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "9800", rsp: "9800" },
    { ddp: "Formula A", sp: "Formula I", rsp: "Formula A" },
    // 350
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    // 360
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula I", rsp: "129999" },
    { ddp: "Formula A", sp: "12000", rsp: "12000" },
    // 370
    { ddp: "Formula A", sp: "7500", rsp: "7500" },
    { ddp: "Formula A", sp: "7500", rsp: "7500" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "2600", rsp: "2750" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    // 380
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "3500" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 390
    { ddp: "Formula A", sp: "Formula F", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula K", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula A", rsp: "750" },
    { ddp: "Formula A", sp: "Formula A", rsp: "2500" },
    // 400
    { ddp: "Formula A", sp: "Formula A", rsp: "3500" },
    { ddp: "Formula A", sp: "Formula A", rsp: "3500" },
    { ddp: "Formula A", sp: "Formula B", rsp: "5500" },
    { ddp: "Formula A", sp: "Formula B", rsp: "0" },
    { ddp: "Formula A", sp: "Formula B", rsp: "0" },
    { ddp: "Formula A", sp: "Formula B", rsp: "0" },
    { ddp: "Formula A", sp: "Formula B", rsp: "0" },
    { ddp: "Formula A", sp: "Formula B", rsp: "0" },
    { ddp: "Formula A", sp: "Formula B", rsp: "0" },
    { ddp: "Formula A", sp: "Formula B", rsp: "0" },
    // 410
    { ddp: "Formula A", sp: "Formula B", rsp: "0" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    // 420
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula B", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
    { ddp: "Formula A", sp: "Formula E", rsp: "Formula A" },
];
